services: 
  backend:

    build: 
      context: ./backend
      dockerfile: backend_Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0  --port 8000 --reload

    environment:
      - MY_PROJECT=This is my project
      - PORT=8000
    env_file:
      - .env.sample

    develop:
      watch:
       - action: rebuild
         path: backend/backend_Dockerfile
       - action: sync
         path: backend/src
         target: /app
  
  db_service:
    image: postgres:latest
    ports:
      - 5432:5432
    # env_file:
    #   - .env_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=mydb
    volumes:
      - dc_man_db_vol:/var/lib/postgresql/data

  static_html:
    build: 
      context: ./static_html
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python -m http.server 8000

volumes:
   dc_man_db_vol: 
